@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Otto Souza",
    "email": "otto@gmail.com",
    "password": "12345"
}

###

# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "otto@gmail.com",
    "password": "12345"
}

###

# @name questions

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergufdsfnt3",
    "content": "Conteudo dafds pergunta3"
}